import { Link } from "wouter";
import { PublicLayout } from "@/components/PublicLayout";

const SECTIONS: { title: string; body: string[] }[] = [
  {
    title: "1. Who these terms apply to",
    body: [
      "Black Heritage Events runs this platform at blackheritage.africa. These terms are an agreement between you and Black Heritage Events. They apply whether you buy a ticket, list an event, run a vendor or professional profile, work gate staff, or just browse.",
      "You must be at least 18 to create an account, or 13 or older with permission from a parent or guardian who accepts these terms for you. Organizers and vendors must be 18 and legally able to enter contracts.",
      "By creating an account or buying a ticket you accept these terms. If you do not accept them, do not use the platform.",
    ],
  },
  {
    title: "2. Accounts",
    body: [
      "Give accurate details when you register and keep your password private. You are responsible for what happens on your account, including actions by your team members if you add them.",
      "Organizers can add team members with limited roles: event managers, finance staff, and entry staff. You choose them, you are responsible for what they do.",
      "Tell us straight away if someone uses your account without permission. We can suspend or close accounts that break these terms.",
    ],
  },
  {
    title: "3. Tickets and purchases",
    body: [
      "Tickets are sold by the event organizer, not by Black Heritage Events. The organizer sets prices, tiers, quantities, and sale windows. We process the payment and deliver the ticket.",
      "Each ticket carries a unique code generated by the system. The code is single-use, tied to one transaction, and cannot be duplicated or moved to another ticket. Present the code at the gate on your phone or as a printout.",
      "A purchase is complete when the payment gateway confirms it. We email your ticket within 60 seconds of that confirmation. If it does not arrive, check spam, then re-download from your tickets page.",
      "Do not resell tickets through unofficial channels. Organizers set their own resale rules; a ticket resold in breach of those rules can be refused at the gate.",
    ],
  },
  {
    title: "4. Refunds",
    body: [
      "Refund decisions belong to the organizer. Whether an event is cancelled, rescheduled, or you simply cannot attend, the organizer decides and we execute.",
      "When an organizer approves a refund, we return the money through the original payment method and email you. Payment processor fees may be deducted where the organizer chooses to pass them on.",
      "Complimentary tickets issued by an organizer can be voided by that organizer at any time.",
    ],
  },
  {
    title: "5. Organizers",
    body: [
      "If you list events, you confirm you own or are licensed to run them, that event details you publish are accurate, and that you will honour every valid ticket sold.",
      "You are responsible for your event running safely and lawfully, including any licences, security, and venue rules. We provide the ticketing system; we do not run your event.",
      "We charge a commission on ticket sales. The rate is shown to you before you publish and is deducted from your settlement. Complimentary tickets carry no commission.",
      "Do not use the platform to sell anything illegal, fraudulent, or that infringes other people's rights. We can unpublish or archive events that break these terms.",
    ],
  },
  {
    title: "6. Vendors, talents, and professionals",
    body: [
      "Vendor, talent, and professional profiles are directory listings. Clients contact and pay you directly, on the platform or off it. You are responsible for the work you agree to do, its quality, and any contract between you and your client.",
      "Keep your profile accurate: your category, portfolio, prices, and service area. A profile that misleads people can be unpublished.",
      "Reviews on your profile must come from real people with real experience of your work. Do not buy, trade, or write fake reviews, and do not pressure anyone into removing an honest one.",
    ],
  },
  {
    title: "7. Payments and money",
    body: [
      "Payments run through our licensed payment processor. We do not store your card details.",
      "Money from ticket sales is settled to organizers after the event, minus platform commission and processor fees. Vendor and entertainment bookings carry a commission where agreed. Sponsor packages are billed as agreed in the package.",
      "Promoter commission is not platform revenue. It is a share an organizer chooses to give a promoter from the organizer's own ticket revenue. We track it and pay it out on the organizer's instruction.",
      "We can hold a settlement while we investigate fraud, chargebacks, or a breach of these terms.",
    ],
  },
  {
    title: "8. Acceptable use",
    body: [
      "Do not misuse the platform: no scraping at scale, no interference with gate verification, no attempts to bypass single-use ticket codes, no uploading of content you have no right to share, and no harassment of other users.",
      "Content you upload (event images, portfolio photos and videos, profile details) stays yours. You give us permission to display it on the platform and in listings until you delete it or your account closes.",
      "We can remove content that breaks these terms or the law.",
    ],
  },
  {
    title: "9. When things go wrong",
    body: [
      "We work hard to keep the platform available and correct, but we provide it as is. To the fullest extent the law allows, we are not liable for indirect or consequential losses: missed events, lost profit, lost goodwill, and similar.",
      "Our total liability to you is capped at the greater of the fees you paid us in the six months before the claim, or the value of the affected ticket.",
      "Nothing in these terms limits liability that cannot legally be limited.",
    ],
  },
  {
    title: "10. Closing accounts and changes",
    body: [
      "You can close your account any time from settings or by contacting us. Tickets you already bought stay valid unless the organizer says otherwise.",
      "We can update these terms as the platform grows. We will give at least 14 days notice of material changes by email or on the platform. Continuing to use the platform after that means you accept the new terms.",
      "These terms are governed by the laws of the Federal Republic of Nigeria, and Nigerian courts have exclusive jurisdiction over disputes.",
    ],
  },
];

export default function Terms() {
  return (
    <PublicLayout>
      <div className="mx-auto w-full max-w-3xl px-4 py-14 md:px-8 md:py-20">
        <p className="text-xs font-semibold uppercase tracking-[0.18em] text-gold">
          Legal
        </p>
        <h1 className="mt-2 font-display text-3xl font-bold text-ink md:text-4xl">
          Terms of service
        </h1>
        <p className="mt-3 text-sm text-muted-ink">
          Last updated: 22 September 2026. Questions about anything here? Write
          to hello@blackheritage.africa and a person will answer.
        </p>

        <div className="mt-10 space-y-10">
          {SECTIONS.map((s) => (
            <section key={s.title}>
              <h2 className="font-display text-lg font-bold text-ink md:text-xl">
                {s.title}
              </h2>
              <div className="mt-3 space-y-3">
                {s.body.map((p, i) => (
                  <p key={i} className="text-sm leading-relaxed text-muted-ink">
                    {p}
                  </p>
                ))}
              </div>
            </section>
          ))}
        </div>

        <p className="mt-14 text-sm text-muted-ink">
          Also read the{" "}
          <Link href="/privacy" className="text-gold underline-offset-4 hover:underline">
            privacy policy
          </Link>
          . It explains what we do with your data.
        </p>
      </div>
    </PublicLayout>
  );
}
